command: [
  "uvicorn",
  "server.app:app"
]
env:
  - name: 'MLFLOW_TRACKING_URI'
    value: 'databricks'
  - name: 'MLFLOW_EXPERIMENT_ID'
    value: '1879320556980726'
  - name: 'LOW_ACCURACY_RESULTS_URL'
    value: 'placeholder-low-accuracy-url'
  - name: 'REGRESSION_RESULTS_URL'
    value: 'placeholder-regression-url'
  - name: 'METRICS_RESULT_URL'
    value: 'placeholder-metrics-url'
  - name: 'LLM_MODEL'
    value: 'databricks-claude-3-7-sonnet'
  - name: 'UC_CATALOG'
    value: 'nethra_ranganathan'
  - name: 'UC_SCHEMA'
    value: 'mlflow_dc_2'
  - name: 'MLFLOW_ENABLE_ASYNC_TRACE_LOGGING'
    value: 'false'
  - name: 'MLFLOW_TRACING_SQL_WAREHOUSE_ID'
    value: 'placeholder-sql-warehouse-id'
  - name: 'MLFLOW_TRACING_DESTINATION'
    value: 'nethra_ranganathan.mlflow_dc_2'
  - name: 'PROMPT_NAME'
    value: 'dc_assistant_system_prompt'
  - name: 'PROMPT_ALIAS'
    value: 'production'
  - name: 'REGRESSION_BASELINE_RUN_ID'
    value: 'placeholder-regression-baseline-run-id'
  - name: 'FIX_QUALITY_BASELINE_RUN_ID'
    value: 'placeholder-fix-quality-baseline-run-id'
  - name: 'SAMPLE_LABELING_SESSION_ID'
    value: 'placeholder-sample-labeling-session-id'
  - name: 'SAMPLE_REVIEW_APP_URL'
    value: 'placeholder-sample-review-app-url'
  - name: 'SAMPLE_LABELING_TRACE_ID'
    value: 'placeholder-sample-labeling-trace-id'
  - name: 'SAMPLE_TRACE_ID'
    value: 'tr-da4dfb0dc7668dbccd0f8ba28e3e56d5'
  - name: 'LHA_SOURCE_CODE_PATH'
    value: '/Workspace/Users/nethra.ranganathan@databricks.com/mlflow-demo'
  - name: 'NOTEBOOK_URL_0_demo_overview'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/808413184221629'
  - name: 'NOTEBOOK_URL_1_observe_with_traces'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/808413184221670'
  - name: 'NOTEBOOK_URL_2_create_quality_metrics'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/808413184221674'
  - name: 'NOTEBOOK_URL_3_find_fix_quality_issues'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/808413184221656'
  - name: 'NOTEBOOK_URL_4_human_review'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/808413184221726'
  - name: 'NOTEBOOK_URL_5_production_monitoring'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/808413184221774'
