command: [
  "uvicorn",
  "server.app:app"
]
env:
  - name: 'MLFLOW_TRACKING_URI'
    value: 'databricks'
  - name: 'MLFLOW_EXPERIMENT_ID'
    value: '3301487308147308'
  - name: 'LOW_ACCURACY_RESULTS_URL'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/ml/experiments/3301487308147308/evaluation-runs?selectedRunUuid=7d9bfc5c929c4d1f8ea10b6a570317dc&compareToRunUuid=816aefcc5d3a4f0ca0739b3f1f569526'
  - name: 'REGRESSION_RESULTS_URL'
    value: 'placeholder-regression-url'
  - name: 'METRICS_RESULT_URL'
    value: 'placeholder-metrics-url'
  - name: 'LLM_MODEL'
    value: 'databricks-claude-sonnet-4-6'
  - name: 'UC_CATALOG'
    value: 'amine_elhelou'
  - name: 'UC_SCHEMA'
    value: 'mlflow3-demo-nfl-v2'
  - name: 'MLFLOW_ENABLE_ASYNC_TRACE_LOGGING'
    value: 'false'
  - name: 'PROMPT_NAME'
    value: 'dc_assistant_system_prompt'
  - name: 'PROMPT_ALIAS'
    value: 'production'
  - name: 'REGRESSION_BASELINE_RUN_ID'
    value: '8136cdb72d664267811cd4ff0fc5b636'
  - name: 'FIX_QUALITY_BASELINE_RUN_ID'
    value: '816aefcc5d3a4f0ca0739b3f1f569526'
  - name: 'SAMPLE_LABELING_SESSION_ID'
    value: '7ed19c63-8d0a-49ce-8495-748fe2267bf8'
  - name: 'SAMPLE_REVIEW_APP_URL'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/ml/review-v2/5194051e923b41f690bbec401dbd29d4/tasks/labeling/7ed19c63-8d0a-49ce-8495-748fe2267bf8'
  - name: 'SAMPLE_LABELING_TRACE_ID'
    value: 'trace:/amine_elhelou.mlflow3-demo-nfl/dc6f91faa867590e7c1a8eec6adf3779'
  - name: 'SAMPLE_TRACE_ID'
    value: 'trace:/amine_elhelou.mlflow3-demo-nfl/dc6f91faa867590e7c1a8eec6adf3779'
  - name: 'LHA_SOURCE_CODE_PATH'
    value: '/Workspace/Users/amine.elhelou@databricks.com/mlflow-nfl-demo-app-aeh'
  - name: 'NOTEBOOK_URL_0_demo_overview'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/1078459371915407'
  - name: 'NOTEBOOK_URL_1_observe_with_traces'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/1078459371915368'
  - name: 'NOTEBOOK_URL_2_create_quality_metrics'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/1078459371915338'
  - name: 'NOTEBOOK_URL_3_find_fix_quality_issues'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/1078459371915393'
  - name: 'NOTEBOOK_URL_4_human_review'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/1078459371915403'
  - name: 'NOTEBOOK_URL_5_production_monitoring'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/1078459371915479'
